In [42]:

def spl(p):
    L=0
    R=0
    spl=0

    for i in range(len(p)):
        if p[i] =='(':
            L +=1
        elif p[i] == ')':
            R +=1

        if R==L:
            spl=i
            break


    u = p[:spl+1]
    v = p[spl+1:]
    return u,v

In [14]:
spl(')(()(()())()')

[')(', '()(()())()']

In [43]:
p = ')(()()))(()('

In [29]:
p= p.replace('()','')
p

'))(('

In [35]:
def TF(p):
    while True:
        a = p.replace('()','')
        if a=='':
            return True
        elif p==a:
            return False
        else:
            p=a

In [36]:
TF(')(')

False

In [37]:
TF('()')

True

In [38]:
p=')('

p='(' + p

In [75]:
def rp(u):
    u=u[1:-1]
    print(u)
    u=u.replace('(','L',1000)
    print(u)
    u=u.replace(')','R',1000)
    print(u)
    u=u.replace('L',')',1000)
    print(u)
    u=u.replace('R','(',1000)
    print(u)
    return u

In [76]:
rp('(((())()()()))')

((())()()())
LLL))L)L)L))
LLLRRLRLRLRR
)))RR)R)R)RR
)))(()()()((

')))(()()()(('

L))L)L)L)L)L)L)

In [47]:
u,v= spl(p)

print(u,v)

print(TF(u))

if TF(u) == True:
    spl(v)
    
elif TF(u) ==False:

)( ()()))(()(
False

In [121]:
def solution(p):
    u=''
    
    u1,v = spl(p)
    
    if TF(u1) == True:
        u=u+u1
        u1,v = spl(v)
    
    elif TF(u1) == False:
        st='('+v+')'+rp(u)

In [78]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [83]:
data = pd.read_csv('data-01-test-score.csv',header=None)

In [90]:
type(data)

pandas.core.frame.DataFrame

In [141]:
x_data = data.iloc[:,0:3].values.tolist()
x_data

[[73, 80, 75],
 [93, 88, 93],
 [89, 91, 90],
 [96, 98, 100],
 [73, 66, 70],
 [53, 46, 55],
 [69, 74, 77],
 [47, 56, 60],
 [87, 79, 90],
 [79, 70, 88],
 [69, 70, 73],
 [70, 65, 74],
 [93, 95, 91],
 [79, 80, 73],
 [70, 73, 78],
 [93, 89, 96],
 [78, 75, 68],
 [81, 90, 93],
 [88, 92, 86],
 [78, 83, 77],
 [82, 86, 90],
 [86, 82, 89],
 [78, 83, 85],
 [76, 83, 71],
 [96, 93, 95]]

In [147]:
y_data = data.iloc[:,3:].values.tolist()
y_data

[[152],
 [185],
 [180],
 [196],
 [142],
 [101],
 [149],
 [115],
 [175],
 [164],
 [141],
 [141],
 [184],
 [152],
 [148],
 [192],
 [147],
 [183],
 [177],
 [159],
 [177],
 [175],
 [175],
 [149],
 [192]]

In [149]:
y_data = [i[0] for i in y_data]

In [150]:
y_data

[152,
 185,
 180,
 196,
 142,
 101,
 149,
 115,
 175,
 164,
 141,
 141,
 184,
 152,
 148,
 192,
 147,
 183,
 177,
 159,
 177,
 175,
 175,
 149,
 192]

In [151]:
with tf.Graph().as_default():
    x = tf.placeholder(tf.float32, shape=[None,3])
    y = tf.placeholder(tf.float32, shape=None)
    
    w = tf.Variable([[0,0,0]],dtype=tf.float32, name = 'weight')
    b = tf.Variable(0, dtype = tf.float32, name='bias')
    
    y_hat = tf.matmul(w, tf.transpose(x))+b
    
    loss = tf.reduce_mean(tf.square(y-y_hat))
    
    optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.000005)
    train = optimizer.minimize(loss)
    
    init = tf.global_variables_initializer()
    with tf.Session() as sess:
        sess.run(init)
        for step in range(100000):
            sess.run(train, feed_dict={x:x_data,y:y_data})
            if (step % 10000 == 0):
                print(step, sess.run([w]))
        print(step, sess.run([w]))

0 [array([[0.13075799, 0.13147199, 0.1346708 ]], dtype=float32)]
10000 [array([[0.44210383, 0.5178263 , 1.055586  ]], dtype=float32)]
20000 [array([[0.3803473 , 0.52103794, 1.1125603 ]], dtype=float32)]
30000 [array([[0.36293593, 0.5271155 , 1.1236416 ]], dtype=float32)]
40000 [array([[0.3580019, 0.5294192, 1.1262854]], dtype=float32)]
50000 [array([[0.35659337, 0.5301345 , 1.1270558 ]], dtype=float32)]
60000 [array([[0.35625744, 0.53037035, 1.1272513 ]], dtype=float32)]
70000 [array([[0.35624322, 0.5304049 , 1.1273309 ]], dtype=float32)]
80000 [array([[0.3562352 , 0.53043723, 1.1274067 ]], dtype=float32)]
90000 [array([[0.3562282, 0.5304693, 1.1274812]], dtype=float32)]
99999 [array([[0.3562212, 0.5304979, 1.127559 ]], dtype=float32)]

s

In [175]:
ins_data = pd.read_csv('insurance.csv')

ins_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [176]:
sex_dummy = pd.get_dummies(ins_data['sex'])
smoker_dummy = pd.get_dummies(ins_data['smoker'])
region_dummy = pd.get_dummies(ins_data['region'])

In [177]:
ins_data = pd.concat([ins_data,sex_dummy,smoker_dummy,region_dummy],axis=1)
ins_data

,age,sex,bmi,children,smoker,region,charges,female,male,no,yes,northeast,northwest,southeast,southwest
0,19,female,27.900,0,yes,southwest,16884.92400,1,0,0,1,0,0,0,1
1,18,male,33.770,1,no,southeast,1725.55230,0,1,1,0,0,0,1,0
2,28,male,33.000,3,no,southeast,4449.46200,0,1,1,0,0,0,1,0
3,33,male,22.705,0,no,northwest,21984.47061,0,1,1,0,0,1,0,0
4,32,male,28.880,0,no,northwest,3866.85520,0,1,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,0,1,1,0,0,1,0,0
1334,18,female,31.920,0,no,northeast,2205.98080,1,0,1,0,1,0,0,0
1335,18,female,36.850,0,no,southeast,1629.83350,1,0,1,0,0,0,1,0
1336,21,female,25.800,0,no,southwest,2007.94500,1,0,1,0,0,0,0,1
1337,61,female,29.070,0,yes,northwest,29141.36030,1,0,0,1,0,1,0,0

In [178]:
x_data = ins_data.iloc[:,[0,2,3,7,8,9,10,11,12,13,14]]
x_data[:5]

,age,bmi,children,female,male,no,yes,northeast,northwest,southeast,southwest
0,19,27.900,0,1,0,0,1,0,0,0,1
1,18,33.770,1,0,1,1,0,0,0,1,0
2,28,33.000,3,0,1,1,0,0,0,1,0
3,33,22.705,0,0,1,1,0,0,1,0,0
4,32,28.880,0,0,1,1,0,0,1,0,0

In [179]:
y_data = ins_data['charges']
y_data[:5]

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [188]:
with tf.Graph().as_default():
    x = tf.placeholder(tf.float32, shape=[None,11])
    y = tf.placeholder(tf.float32, shape=None)
    
    w = tf.Variable(tf.random_normal([11,1]), name='weight')
    b = tf.Variable(0, dtype = tf.float32, name='bias')
    
    y_hat = tf.matmul(x, w) + b
    
    loss = tf.reduce_mean(tf.square(y-y_hat))
    
    optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.00005)
    train = optimizer.minimize(loss)
    
    init = tf.global_variables_initializer()
    with tf.Session() as sess:
        sess.run(init)
        for step in range(5000):
            sess.run(train, feed_dict={x:x_data,y:y_data})
            if (step % 400 == 0):
                print(step, sess.run([w]))
        print(step, sess.run([w]))

0 [array([[ 5.2485306e+01],
       [ 4.1437336e+01],
       [ 6.7634881e-01],
       [ 6.1949921e-01],
       [-6.0267389e-02],
       [ 1.2378217e+00],
       [-3.8327885e-01],
       [-2.0383418e-02],
       [ 6.7616439e-01],
       [ 8.5204875e-01],
       [ 5.9829795e-01]], dtype=float32)]
400 [array([[ 71.71047  ],
       [324.3143   ],
       [ 22.121292 ],
       [ 13.456894 ],
       [ 11.113672 ],
       [ 19.784397 ],
       [  5.081468 ],
       [  9.753794 ],
       [ 10.457725 ],
       [ -0.4470003],
       [  6.352952 ]], dtype=float32)]
800 [array([[ 67.3691   ],
       [328.45044  ],
       [ 35.677773 ],
       [ 23.202015 ],
       [ 18.211325 ],
       [ 32.779434 ],
       [  8.929229 ],
       [ 18.478106 ],
       [ 19.132238 ],
       [ -5.1220026],
       [ 10.471904 ]], dtype=float32)]
1200 [array([[ 66.87708  ],
       [327.3996   ],
       [ 48.311558 ],
       [ 32.83722  ],
       [ 25.23339  ],
       [ 45.571617 ],
       [ 12.7943325],
       [ 27.122469 ],
       [ 27.710484 ],
       [ -9.755038 ],
       [ 14.539595 ]], dtype=float32)]
1600 [array([[ 66.510864],
       [326.2123  ],
       [ 60.16384 ],
       [ 42.40206 ],
       [ 32.248737],
       [ 58.241653],
       [ 16.704466],
       [ 35.691963],
       [ 36.19968 ],
       [-14.273281],
       [ 18.579355]], dtype=float32)]
2000 [array([[ 66.15661 ],
       [325.04144 ],
       [ 71.28248 ],
       [ 51.898865],
       [ 39.259598],
       [ 70.79405 ],
       [ 20.659739],
       [ 44.187557],
       [ 44.601753],
       [-18.676588],
       [ 22.592688]], dtype=float32)]
2400 [array([[ 65.810356],
       [323.89053 ],
       [ 81.71003 ],
       [ 61.328842],
       [ 46.266125],
       [ 83.23087 ],
       [ 24.659395],
       [ 52.610085],
       [ 52.9184  ],
       [-22.966982],
       [ 26.58038 ]], dtype=float32)]
2800 [array([[ 65.47083 ],
       [322.75998 ],
       [ 91.48636 ],
       [ 70.69308 ],
       [ 53.268322],
       [ 95.55403 ],
       [ 28.702627],
       [ 60.96035 ],
       [ 61.151283],
       [-27.146519],
       [ 30.54317 ]], dtype=float32)]
3200 [array([[ 65.13875 ],
       [321.64737 ],
       [100.64922 ],
       [ 79.99264 ],
       [ 60.26617 ],
       [107.765434],
       [ 32.78868 ],
       [ 69.23918 ],
       [ 69.30198 ],
       [-31.217176],
       [ 34.481766]], dtype=float32)]
3600 [array([[ 64.81268 ],
       [320.5532  ],
       [109.23409 ],
       [ 89.22859 ],
       [ 67.2596  ],
       [119.86686 ],
       [ 36.916763],
       [ 77.447334],
       [ 77.372   ],
       [-35.180885],
       [ 38.39679 ]], dtype=float32)]
4000 [array([[ 64.493645],
       [319.4748  ],
       [117.27444 ],
       [ 98.40196 ],
       [ 74.24909 ],
       [131.86017 ],
       [ 41.086094],
       [ 85.5856  ],
       [ 85.362854],
       [-39.03952 ],
       [ 42.288918]], dtype=float32)]
4400 [array([[ 64.18015 ],
       [318.4131  ],
       [124.80183 ],
       [107.51376 ],
       [ 81.23375 ],
       [143.74696 ],
       [ 45.295914],
       [ 93.65474 ],
       [ 93.275925],
       [-42.794876],
       [ 46.15872 ]], dtype=float32)]
4800 [array([[ 63.872215],
       [317.36685 ],
       [131.84596 ],
       [116.56497 ],
       [ 88.21431 ],
       [155.52902 ],
       [ 49.545452],
       [101.65549 ],
       [101.112595],
       [-46.448746],
       [ 50.006786]], dtype=float32)]
4999 [array([[ 63.721584],
       [316.85104 ],
       [135.1792  ],
       [121.045685],
       [ 91.68523 ],
       [161.35214 ],
       [ 51.67415 ],
       [105.61062 ],
       [104.98328 ],
       [-48.22928 ],
       [ 51.91327 ]], dtype=float32)]

In [193]:
with tf.Graph().as_default():
    #tf.set_random_seed(77777)

    x = tf.placeholder(tf.float32, shape=[None,11])
    y = tf.placeholder(tf.float32, shape=[None])
    
    W = tf.Variable(tf.random_normal([11,1]), name='weight')
    b = tf.Variable(tf.random_normal([1]), name='bias')
    
    y_hat = tf.matmul(x, W) + b
    
    loss = tf.reduce_mean(tf.square(y - y_hat))
     
    optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-4)
    train = optimizer.minimize(loss)
    
    init = tf.global_variables_initializer()
    with tf.Session() as sess:
        sess.run(init)
        for step in range(50000):
            cost, hypothesis, _ = sess.run([loss, y_hat, train], feed_dict={x:x_data, y:y_data})
            if (step % 10000 == 0):
                print(step, cost, sess.run([W, b]))
        print(step, cost, sess.run([W, b]))

0 321972960.0 [array([[104.89691   ],
       [ 80.729576  ],
       [  0.93121743],
       [  0.7179217 ],
       [  0.75734353],
       [  1.9585546 ],
       [  1.4487252 ],
       [  1.0255369 ],
       [  0.9032116 ],
       [  0.4936162 ],
       [ -0.34293377]], dtype=float32), array([3.9134417], dtype=float32)]
10000 150511040.0 [array([[  54.7997 ],
       [ 284.24036],
       [ 216.05498],
       [ 423.18066],
       [ 348.604  ],
       [ 539.09576],
       [ 234.62044],
       [ 361.7384 ],
       [ 352.18607],
       [-124.53522],
       [ 182.99937]], dtype=float32), array([774.22266], dtype=float32)]
20000 149527380.0 [array([[  46.402267],
       [ 249.15273 ],
       [ 194.2255  ],
       [ 751.24866 ],
       [ 666.90106 ],
       [ 911.9293  ],
       [ 508.16037 ],
       [ 604.33887 ],
       [ 585.4326  ],
       [-105.74271 ],
       [ 334.72504 ]], dtype=float32), array([1420.5867], dtype=float32)]
30000 148823170.0 [array([[  39.869   ],
       [ 218.90784 ],
       [ 167.14366 ],
       [1025.3708  ],
       [ 949.1074  ],
       [1195.7908  ],
       [ 780.61584 ],
       [ 774.1039  ],
       [ 749.9585  ],
       [ -16.118408],
       [ 467.1343  ]], dtype=float32), array([1976.9133], dtype=float32)]
40000 148296590.0 [array([[  34.53771],
       [ 192.45703],
       [ 144.54865],
       [1261.2649 ],
       [1195.7572 ],
       [1424.7267 ],
       [1034.228  ],
       [ 897.45514],
       [ 871.21063],
       [ 104.70595],
       [ 584.2532 ]], dtype=float32), array([2459.4597], dtype=float32)]
49999 147895440.0 [array([[  30.074999],
       [ 169.24501 ],
       [ 125.681244],
       [1466.737   ],
       [1410.7843  ],
       [1616.3679  ],
       [1263.0833  ],
       [ 990.4219  ],
       [ 964.11475 ],
       [ 235.31467 ],
       [ 688.27704 ]], dtype=float32), array([2879.9583], dtype=float32)]

In [205]:
x_data = [[1,2],
         [2,3],
         [3,1],
         [4,3],
         [5,3],
         [6,2]]

y_data = [[0],
         [0],
         [0],
         [1],
         [1],
         [1]]

X = tf.placeholder(tf.float32, shape=[None,2])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([2,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')


hypothesis = tf.sigmoid(tf.matmul(X,W) + b)   #1.0 / (1+ np.exp(-(tf.matmul(X,W)+b)))
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X:x_data, Y:y_data})
        if step % 200 == 0:
            print(step, cost_val)
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data})
    
    print(f'\n Hypothesis = \n {h}',
         f'\n\n Predicted =  \n {c}',
         f'\n\n Accuracy = {a}')

0 1.0088991
200 0.7366367
400 0.6316082
600 0.5779335
800 0.54377073
1000 0.51807207
1200 0.49660078
1400 0.4775522
1600 0.4600902
1800 0.44379914
2000 0.42845786
2200 0.41393998
2400 0.4001664
2600 0.38708195
2800 0.37464425
3000 0.36281726
3200 0.3515687
3400 0.34086847
3600 0.3306879
3800 0.3209995
4000 0.31177697
4200 0.30299476
4400 0.29462877
4600 0.28665584
4800 0.2790539
5000 0.27180204
5200 0.26488042
5400 0.25827032
5600 0.2519542
5800 0.24591535
6000 0.24013817
6200 0.23460792
6400 0.22931094
6600 0.22423418
6800 0.21936561
7000 0.21469368
7200 0.2102079
7400 0.20589823
7600 0.20175523
7800 0.19777016
8000 0.19393484
8200 0.19024146
8400 0.18668276
8600 0.18325199
8800 0.17994271
9000 0.17674893
9200 0.17366493
9400 0.17068553
9600 0.16780566
9800 0.16502059
10000 0.16232596

 Hypothesis =
 [[0.03631607]
 [0.16577834]
 [0.33052385]
 [0.76989406]
 [0.93210566]
 [0.9776953 ]]

 Predicted =
 [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]

 Accuracy = 1.0

In [207]:
datacsv = pd.read_csv('data-03-diabetes.csv',header=None)
datacsv

,0,1,2,3,4,5,6,7,8
0,-0.294118,0.487437,0.180328,-0.292929,0.000000,0.001490,-0.531170,-0.033333,0
1,-0.882353,-0.145729,0.081967,-0.414141,0.000000,-0.207153,-0.766866,-0.666667,1
2,-0.058824,0.839196,0.049180,0.000000,0.000000,-0.305514,-0.492741,-0.633333,0
3,-0.882353,-0.105528,0.081967,-0.535354,-0.777778,-0.162444,-0.923997,0.000000,1
4,0.000000,0.376884,-0.344262,-0.292929,-0.602837,0.284650,0.887276,-0.600000,0
...,...,...,...,...,...,...,...,...,...
754,0.176471,0.015075,0.245902,-0.030303,-0.574468,-0.019374,-0.920581,0.400000,1
755,-0.764706,0.226131,0.147541,-0.454545,0.000000,0.096870,-0.776260,-0.800000,1
756,-0.411765,0.216080,0.180328,-0.535354,-0.735225,-0.219076,-0.857387,-0.700000,1
757,-0.882353,0.266332,-0.016393,0.000000,0.000000,-0.102832,-0.768574,-0.133333,0
758,-0.882353,-0.065327,0.147541,-0.373737,0.000000,-0.093890,-0.797609,-0.933333,1

In [208]:
x_data = datacsv.iloc[:,0:8]
x_data

,0,1,2,3,4,5,6,7
0,-0.294118,0.487437,0.180328,-0.292929,0.000000,0.001490,-0.531170,-0.033333
1,-0.882353,-0.145729,0.081967,-0.414141,0.000000,-0.207153,-0.766866,-0.666667
2,-0.058824,0.839196,0.049180,0.000000,0.000000,-0.305514,-0.492741,-0.633333
3,-0.882353,-0.105528,0.081967,-0.535354,-0.777778,-0.162444,-0.923997,0.000000
4,0.000000,0.376884,-0.344262,-0.292929,-0.602837,0.284650,0.887276,-0.600000
...,...,...,...,...,...,...,...,...
754,0.176471,0.015075,0.245902,-0.030303,-0.574468,-0.019374,-0.920581,0.400000
755,-0.764706,0.226131,0.147541,-0.454545,0.000000,0.096870,-0.776260,-0.800000
756,-0.411765,0.216080,0.180328,-0.535354,-0.735225,-0.219076,-0.857387,-0.700000
757,-0.882353,0.266332,-0.016393,0.000000,0.000000,-0.102832,-0.768574,-0.133333
758,-0.882353,-0.065327,0.147541,-0.373737,0.000000,-0.093890,-0.797609,-0.933333

In [215]:
y_data = datacsv.iloc[:,8:]
y_data

     8
0    0
1    1
2    0
3    1
4    0
..  ..
754  1
755  1
756  1
757  0
758  1

[759 rows x 1 columns]

In [218]:
X = tf.placeholder(tf.float32, shape=[None,8])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([8,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')


hypothesis = tf.sigmoid(tf.matmul(X,W) + b)   #1.0 / (1+ np.exp(-(tf.matmul(X,W)+b)))
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.005).minimize(cost)
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100001):
        cost_val, _ = sess.run([cost, train], feed_dict={X:x_data, Y:y_data})
        if step % 10000 == 0:
            print(step, cost_val)
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data})
    
    print(f'\n Hypothesis = \n {h}',
         f'\n\n Predicted =  \n {c}',
         f'\n\n Accuracy = {a}')

0 1.083681
10000 0.49543446
20000 0.47829428
30000 0.47455153
40000 0.47321275
50000 0.4725836
60000 0.4722417
70000 0.4720403
80000 0.47191545
90000 0.47183535
100000 0.47178274

 Hypothesis =
 [[0.36015284]
 [0.9554049 ]
 [0.19062418]
 [0.96234524]
 [0.07648924]
 [0.82630527]
 [0.9541341 ]
 [0.58136356]
 [0.1823124 ]
 [0.583943  ]
 [0.7466218 ]
 [0.11261946]
 [0.26544303]
 [0.20298764]
 [0.78108   ]
 [0.38564676]
 [0.7893962 ]
 [0.7839775 ]
 [0.8194282 ]
 [0.56983924]
 [0.7201365 ]
 [0.06015188]
 [0.7139093 ]
 [0.6785675 ]
 [0.2933938 ]
 [0.96040636]
 [0.60974354]
 [0.6981409 ]
 [0.7107138 ]
 [0.39369196]
 [0.9689268 ]
 [0.94569534]
 [0.6403582 ]
 [0.86783   ]
 [0.348504  ]
 [0.6876081 ]
 [0.8398852 ]
 [0.51827073]
 [0.3323489 ]
 [0.32030892]
 [0.90719247]
 [0.09779441]
 [0.37963307]
 [0.02413347]
 [0.54818004]
 [0.96176076]
 [0.6940171 ]
 [0.7317572 ]
 [0.96842563]
 [0.9490379 ]
 [0.9581091 ]
 [0.18626755]
 [0.28311133]
 [0.98040235]
 [0.11868709]
 [0.43309927]
 [0.08623356]
 [0.66962636]
 [0.90019953]
 [0.4966925 ]
 [0.977463  ]
 [0.7138565 ]
 [0.67893994]
 [0.89558655]
 [0.6510648 ]
 [0.57641214]
 [0.9772336 ]
 [0.7175428 ]
 [0.86848426]
 [0.66383445]
 [0.22070196]
 [0.7293521 ]
 [0.9478092 ]
 [0.9477708 ]
 [0.92955315]
 [0.80739737]
 [0.31235206]
 [0.90450823]
 [0.9192564 ]
 [0.9437859 ]
 [0.91023713]
 [0.8790108 ]
 [0.30949223]
 [0.8363218 ]
 [0.53973216]
 [0.87090504]
 [0.34330726]
 [0.9298737 ]
 [0.97192204]
 [0.789842  ]
 [0.79549026]
 [0.7284917 ]
 [0.7594813 ]
 [0.5359145 ]
 [0.9263629 ]
 [0.98781216]
 [0.90998995]
 [0.5194825 ]
 [0.16705385]
 [0.65893966]
 [0.75076354]
 [0.97716177]
 [0.78030884]
 [0.76144457]
 [0.9608437 ]
 [0.65811616]
 [0.933807  ]
 [0.8426879 ]
 [0.4127862 ]
 [0.26950437]
 [0.95495325]
 [0.9049033 ]
 [0.3390475 ]
 [0.46985453]
 [0.64541924]
 [0.85792375]
 [0.89846706]
 [0.9553919 ]
 [0.05775511]
 [0.73378843]
 [0.8723813 ]
 [0.6942481 ]
 [0.66475093]
 [0.6550551 ]
 [0.6311356 ]
 [0.8365191 ]
 [0.8392688 ]
 [0.7115906 ]
 [0.43630272]
 [0.3670314 ]
 [0.32716274]
 [0.80003136]
 [0.9621529 ]
 [0.81890166]
 [0.8190701 ]
 [0.87946045]
 [0.4771482 ]
 [0.8080679 ]
 [0.8272343 ]
 [0.73645806]
 [0.8810203 ]
 [0.6605705 ]
 [0.50104856]
 [0.73179245]
 [0.9494315 ]
 [0.76503664]
 [0.4346577 ]
 [0.9583199 ]
 [0.5987323 ]
 [0.85164875]
 [0.21184385]
 [0.31093836]
 [0.04834881]
 [0.14437133]
 [0.9340417 ]
 [0.899701  ]
 [0.9630612 ]
 [0.05817276]
 [0.553591  ]
 [0.78467774]
 [0.55331504]
 [0.89716804]
 [0.45167202]
 [0.83793217]
 [0.57584107]
 [0.677114  ]
 [0.7565807 ]
 [0.9062512 ]
 [0.83286345]
 [0.57227075]
 [0.9175701 ]
 [0.86839557]
 [0.9679853 ]
 [0.15484357]
 [0.8777839 ]
 [0.1173721 ]
 [0.29083955]
 [0.35784495]
 [0.942674  ]
 [0.6267024 ]
 [0.9486406 ]
 [0.9471524 ]
 [0.6343795 ]
 [0.07451892]
 [0.13989478]
 [0.65095305]
 [0.78953695]
 [0.6386651 ]
 [0.8905599 ]
 [0.61143064]
 [0.3164192 ]
 [0.10074502]
 [0.9359344 ]
 [0.3046124 ]
 [0.9116514 ]
 [0.9277111 ]
 [0.7121315 ]
 [0.60416174]
 [0.6561627 ]
 [0.5298657 ]
 [0.7558073 ]
 [0.97105473]
 [0.7680238 ]
 [0.87246   ]
 [0.06937134]
 [0.29644787]
 [0.9207726 ]
 [0.14610824]
 [0.9582883 ]
 [0.20817444]
 [0.21364838]
 [0.3365657 ]
 [0.73153764]
 [0.12641442]
 [0.74272627]
 [0.7309185 ]
 [0.8617973 ]
 [0.65813345]
 [0.08463699]
 [0.34886515]
 [0.763739  ]
 [0.49024236]
 [0.95048845]
 [0.95441115]
 [0.72960854]
 [0.2475254 ]
 [0.01677427]
 [0.5822022 ]
 [0.28010726]
 [0.35154206]
 [0.97433805]
 [0.6335136 ]
 [0.9684067 ]
 [0.13036722]
 [0.07428101]
 [0.23958784]
 [0.8649397 ]
 [0.941111  ]
 [0.9051651 ]
 [0.66642714]
 [0.6552606 ]
 [0.52572757]
 [0.10713542]
 [0.56971973]
 [0.06326017]
 [0.55149513]
 [0.9079368 ]
 [0.68257964]
 [0.77227175]
 [0.9733378 ]
 [0.83734775]
 [0.8022996 ]
 [0.77409077]
 [0.78968835]
 [0.8898953 ]
 [0.29028356]
 [0.3044716 ]
 [0.5008322 ]
 [0.8535552 ]
 [0.65308064]
 [0.6964988 ]
 [0.83029723]
 [0.25262314]
 [0.41008803]
 [0.65677065]
 [0.6367369 ]
 [0.3629279 ]
 [0.93207955]
 [0.8450697 ]
 [0.95664036]
 [0.5729948 ]
 [0.7662991 ]
 [0.85362124]
 [0.8517377 ]
 [0.75676006]
 [0.8921087 ]
 [0.2809636 ]
 [0.54706156]
 [0.69542146]
 [0.35846108]
 [0.87770873]
 [0.23465663]
 [0.5488347 ]
 [0.9609314 ]
 [0.7925011 ]
 [0.8859538 ]
 [0.65919596]
 [0.39874232]
 [0.54808545]
 [0.39536804]
 [0.36070186]
 [0.65989304]
 [0.65528876]
 [0.64804816]
 [0.70939016]
 [0.1471878 ]
 [0.6407826 ]
 [0.93468773]
 [0.41730598]
 [0.70749325]
 [0.7447071 ]
 [0.4416414 ]
 [0.743618  ]
 [0.4721495 ]
 [0.69923484]
 [0.93920267]
 [0.6293962 ]
 [0.69807106]
 [0.86005867]
 [0.5555704 ]
 [0.86201847]
 [0.9715494 ]
 [0.25296864]
 [0.77194345]
 [0.2336353 ]
 [0.77996814]
 [0.84456384]
 [0.731874  ]
 [0.36206883]
 [0.8074851 ]
 [0.7518215 ]
 [0.72852296]
 [0.12113208]
 [0.806007  ]
 [0.87703586]
 [0.63170063]
 [0.9530285 ]
 [0.13965109]
 [0.7981    ]
 [0.9678595 ]
 [0.11289045]
 [0.4495839 ]
 [0.7347828 ]
 [0.26836276]
 [0.11495185]
 [0.8685669 ]
 [0.9472011 ]
 [0.8888564 ]
 [0.6542517 ]
 [0.6928906 ]
 [0.5522495 ]
 [0.7356072 ]
 [0.8690597 ]
 [0.95957977]
 [0.74395066]
 [0.78210604]
 [0.62266195]
 [0.96331763]
 [0.9586483 ]
 [0.74314356]
 [0.25943932]
 [0.6500031 ]
 [0.26059306]
 [0.7849356 ]
 [0.12150431]
 [0.16881773]
 [0.40367258]
 [0.75414383]
 [0.32118037]
 [0.5175694 ]
 [0.843939  ]
 [0.7039918 ]
 [0.90600073]
 [0.971792  ]
 [0.7978395 ]
 [0.05447423]
 [0.41458613]
 [0.8518158 ]
 [0.8645129 ]
 [0.62554836]
 [0.22533008]
 [0.92449534]
 [0.90508807]
 [0.18081728]
 [0.62222344]
 [0.8678861 ]
 [0.9062548 ]
 [0.89266086]
 [0.93281186]
 [0.906352  ]
 [0.9391031 ]
 [0.7045435 ]
 [0.62498486]
 [0.5461644 ]
 [0.857602  ]
 [0.8997214 ]
 [0.13647783]
 [0.8455359 ]
 [0.913537  ]
 [0.29180312]
 [0.61173284]
 [0.9017417 ]
 [0.52188236]
 [0.95931023]
 [0.17842412]
 [0.8712781 ]
 [0.6153011 ]
 [0.921093  ]
 [0.29232964]
 [0.5950579 ]
 [0.7758753 ]
 [0.8632379 ]
 [0.07202503]
 [0.13363445]
 [0.7301949 ]
 [0.8323258 ]
 [0.36789   ]
 [0.81076527]
 [0.41786292]
 [0.29626858]
 [0.88873947]
 [0.40112484]
 [0.96562564]
 [0.8401445 ]
 [0.6262206 ]
 [0.94569135]
 [0.625619  ]
 [0.8192861 ]
 [0.22894418]
 [0.19307485]
 [0.7821642 ]
 [0.3182916 ]
 [0.42469   ]
 [0.9218192 ]
 [0.9411725 ]
 [0.9367193 ]
 [0.96780896]
 [0.74831516]
 [0.9304229 ]
 [0.26102784]
 [0.31881368]
 [0.4843443 ]
 [0.97219056]
 [0.63505316]
 [0.13166168]
 [0.94711155]
 [0.81635725]
 [0.6187185 ]
 [0.81913507]
 [0.00486344]
 [0.9468763 ]
 [0.7986978 ]
 [0.76078606]
 [0.77886987]
 [0.98171854]
 [0.6661005 ]
 [0.76925945]
 [0.8145317 ]
 [0.8433087 ]
 [0.12014294]
 [0.64444935]
 [0.93456984]
 [0.63880026]
 [0.80796576]
 [0.97449434]
 [0.87523407]
 [0.9292189 ]
 [0.6461702 ]
 [0.8136468 ]
 [0.9580121 ]
 [0.74292535]
 [0.6658617 ]
 [0.19602054]
 [0.401272  ]
 [0.5052732 ]
 [0.56603193]
 [0.58043605]
 [0.8201263 ]
 [0.6208808 ]
 [0.81733817]
 [0.8753522 ]
 [0.78262424]
 [0.708373  ]
 [0.4136983 ]
 [0.6069038 ]
 [0.9547062 ]
 [0.8667114 ]
 [0.1557988 ]
 [0.3367989 ]
 [0.4129426 ]
 [0.04784268]
 [0.92712003]
 [0.12236708]
 [0.9126383 ]
 [0.91909444]
 [0.86562574]
 [0.6920355 ]
 [0.919739  ]
 [0.35163575]
 [0.8367523 ]
 [0.9593284 ]
 [0.24974653]
 [0.4062574 ]
 [0.91815376]
 [0.8976664 ]
 [0.6481401 ]
 [0.8262954 ]
 [0.84261906]
 [0.8682799 ]
 [0.1949361 ]
 [0.7667637 ]
 [0.9156121 ]
 [0.70747507]
 [0.8478358 ]
 [0.7361034 ]
 [0.88295436]
 [0.91100204]
 [0.9498478 ]
 [0.5418752 ]
 [0.41159767]
 [0.8198544 ]
 [0.8388496 ]
 [0.98419666]
 [0.7838691 ]
 [0.7067708 ]
 [0.38562602]
 [0.72542596]
 [0.9564605 ]
 [0.9741721 ]
 [0.9209272 ]
 [0.70899385]
 [0.731202  ]
 [0.8110472 ]
 [0.41155154]
 [0.8157643 ]
 [0.8459626 ]
 [0.91179204]
 [0.6004524 ]
 [0.78966606]
 [0.95027757]
 [0.4600813 ]
 [0.53772223]
 [0.6496284 ]
 [0.7286518 ]
 [0.71036863]
 [0.92361677]
 [0.94762516]
 [0.14946336]
 [0.063528  ]
 [0.7491806 ]
 [0.48632407]
 [0.23047799]
 [0.87975436]
 [0.92858136]
 [0.7831223 ]
 [0.9534088 ]
 [0.92688173]
 [0.8041526 ]
 [0.8565451 ]
 [0.76594007]
 [0.48467252]
 [0.8317677 ]
 [0.6268375 ]
 [0.05165851]
 [0.9156871 ]
 [0.9061171 ]
 [0.7811885 ]
 [0.9371625 ]
 [0.86994064]
 [0.9048805 ]
 [0.54815644]
 [0.6742798 ]
 [0.9243367 ]
 [0.8314354 ]
 [0.8713515 ]
 [0.9161365 ]
 [0.61259794]
 [0.7754418 ]
 [0.848618  ]
 [0.5114525 ]
 [0.5572378 ]
 [0.06352055]
 [0.19891685]
 [0.8726876 ]
 [0.6902127 ]
 [0.69257396]
 [0.59401464]
 [0.96085715]
 [0.3918088 ]
 [0.8740136 ]
 [0.21188658]
 [0.9475999 ]
 [0.26874632]
 [0.7807199 ]
 [0.58678234]
 [0.88523376]
 [0.581832  ]
 [0.16364485]
 [0.8066042 ]
 [0.9428363 ]
 [0.30314112]
 [0.9343951 ]
 [0.917564  ]
 [0.90548086]
 [0.853487  ]
 [0.3549329 ]
 [0.26051033]
 [0.6699205 ]
 [0.10889482]
 [0.973225  ]
 [0.2564463 ]
 [0.94727224]
 [0.89008665]
 [0.3081563 ]
 [0.14741582]
 [0.7363001 ]
 [0.36991453]
 [0.8915739 ]
 [0.79258263]
 [0.99055797]
 [0.60292894]
 [0.63905495]
 [0.79985696]
 [0.8694751 ]
 [0.04272008]
 [0.7145065 ]
 [0.84400344]
 [0.876186  ]
 [0.69733846]
 [0.47430113]
 [0.61917067]
 [0.9400157 ]
 [0.6822121 ]
 [0.8035376 ]
 [0.8623119 ]
 [0.8910576 ]
 [0.86192745]
 [0.61365753]
 [0.84985346]
 [0.9240016 ]
 [0.6838937 ]
 [0.9777789 ]
 [0.84295607]
 [0.6199681 ]
 [0.5099712 ]
 [0.8799665 ]
 [0.887639  ]
 [0.39376265]
 [0.66476107]
 [0.12551528]
 [0.5922949 ]
 [0.84868914]
 [0.965322  ]
 [0.82989633]
 [0.73217773]
 [0.7902653 ]
 [0.90177083]
 [0.37846938]
 [0.957336  ]
 [0.55255073]
 [0.88311744]
 [0.3148522 ]
 [0.03875929]
 [0.24445355]
 [0.28506333]
 [0.70057356]
 [0.8529174 ]
 [0.5838559 ]
 [0.7879071 ]
 [0.8198904 ]
 [0.46593362]
 [0.28974697]
 [0.9298167 ]
 [0.93401855]
 [0.27336395]
 [0.72699857]
 [0.12923053]
 [0.43388778]
 [0.76330566]
 [0.6831872 ]
 [0.92987704]
 [0.9889318 ]
 [0.09666106]
 [0.6721711 ]
 [0.6438951 ]
 [0.44767156]
 [0.7220682 ]
 [0.79114294]
 [0.91078794]
 [0.76419675]
 [0.38953775]
 [0.75024426]
 [0.12753502]
 [0.6351349 ]
 [0.47164708]
 [0.9485434 ]
 [0.5973176 ]
 [0.51645803]
 [0.8526457 ]
 [0.7274985 ]
 [0.3912149 ]
 [0.7493872 ]
 [0.6970145 ]
 [0.2762987 ]
 [0.561154  ]
 [0.9127737 ]
 [0.8675264 ]
 [0.5862199 ]
 [0.7497895 ]
 [0.24913344]
 [0.85013807]
 [0.53880084]
 [0.77951336]
 [0.31943342]
 [0.6537482 ]
 [0.8849525 ]
 [0.09188756]
 [0.22821862]
 [0.8724513 ]
 [0.8208865 ]
 [0.82083607]
 [0.9454447 ]
 [0.77874506]
 [0.68823564]
 [0.7242623 ]
 [0.83526886]
 [0.69809437]
 [0.8018663 ]
 [0.47963423]
 [0.4897807 ]
 [0.91328347]
 [0.82276046]
 [0.7168386 ]
 [0.17846107]
 [0.89764035]
 [0.88789546]
 [0.8492793 ]
 [0.7155447 ]
 [0.92317104]
 [0.8664993 ]
 [0.78899455]
 [0.34598577]
 [0.89602566]
 [0.9264474 ]
 [0.34246615]
 [0.10383865]
 [0.7797061 ]
 [0.30140465]
 [0.7852805 ]
 [0.21078268]
 [0.44967467]
 [0.42305872]
 [0.76335955]
 [0.90348035]
 [0.08214957]
 [0.33807063]
 [0.6041878 ]
 [0.5255012 ]
 [0.50146735]
 [0.8129097 ]
 [0.11677906]
 [0.93788636]
 [0.10023557]
 [0.91016394]
 [0.76331586]
 [0.71715456]
 [0.8620399 ]
 [0.73675156]
 [0.9273727 ]]

 Predicted =
 [[0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

 Accuracy = 0.7681159377098083