In [1]:
import pandas as pd

heart = pd.read_csv("heart.csv", index_col=0)
heart

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [2]:
#heart.loc[heart.ChestPain == 'typical','ChestPain'] = 0

In [3]:
heart.dropna(0,how='any',inplace=True)
heart.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           0
Thal         0
AHD          0
dtype: int64

In [4]:
from sklearn.preprocessing import LabelEncoder
heart["ChestPain"] = LabelEncoder().fit_transform(heart["ChestPain"])
heart["Thal"] = LabelEncoder().fit_transform(heart["Thal"])

In [5]:
from sklearn.model_selection import train_test_split
X = heart.iloc[:,:-1]
y = heart.iloc[:,-1:]

In [6]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 297 entries, 1 to 302
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        297 non-null    int64
 1   Sex        297 non-null    int64
 2   ChestPain  297 non-null    int32
 3   RestBP     297 non-null    int64
 4   Chol       297 non-null    int64
 5   Fbs        297 non-null    int64
 6   RestECG    297 non-null    int64
 7   MaxHR      297 non-null    int64
 8   ExAng      297 non-null    int64
 9   Oldpeak    297 non-null    float64
 10  Slope      297 non-null    int64
 11  Ca         297 non-null    float64
 12  Thal       297 non-null    int32
 13  AHD        297 non-null    object
dtypes: float64(2), int32(2), int64(9), object(1)
memory usage: 32.5+ KB

In [114]:
set(heart.ChestPain)

{0, 1, 2, 3}

In [117]:
trainData, testData, trainLabel, testLabel = train_test_split(X, y, random_state=1)

In [118]:
trainData

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal
108,57,1,1,128,229,0,2,150,0,0.4,2,1.0,2
39,55,1,0,132,353,0,0,132,1,1.2,2,1.0,2
121,48,1,0,130,256,1,2,150,1,0.0,1,2.0,2
68,54,1,1,150,232,0,2,165,0,1.6,1,0.0,2
133,29,1,2,130,204,0,2,202,0,0.0,1,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,58,1,0,128,259,0,2,130,1,3.0,2,2.0,2
259,70,1,2,156,245,0,2,143,0,0.0,1,0.0,1
73,62,1,0,120,267,0,0,99,1,1.8,2,2.0,2
239,49,0,2,134,271,0,0,162,0,0.0,2,0.0,1
38,57,1,0,150,276,0,2,112,1,0.6,2,1.0,0

In [50]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=15)
clf.fit(trainData, trainLabel)

C:\Users\ilifo\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=15, p=2,
                     weights='uniform')

In [51]:
print("Test set prediction : {}".format(clf.predict(testData)))
print("Test set accuracy : {:.2f}".format(clf.score(testData, testLabel)))

Test set prediction : ['No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes'
 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'No'
 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes'
 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'No'
 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No']
Test set accuracy : 0.68

In [8]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier

heart = pd.read_csv("heart.csv", index_col=0)
heart.dropna(0,how='any',inplace=True)

heart["ChestPain"] = LabelEncoder().fit_transform(heart["ChestPain"])
heart["Thal"] = LabelEncoder().fit_transform(heart["Thal"])

print(heart.ChestPain)

features = [['Age', 'RestBP', 'Chol', 'Fbs', 'RestECG', 'MaxHR', 'ExAng', 'Oldpeak', 'Slope', 'Ca']]
for feature in features:
    heart[feature] = MinMaxScaler().fit_transform(heart[feature])
    
X = heart.iloc[:,:-1]
#y = heart.iloc[:,-1:]
y = np.array(heart.iloc[:,-1:]).ravel()

trainData, testData, trainLabel, testLabel = train_test_split(X, y, random_state=0)

for i in range(1,30,3):
    clf = KNeighborsClassifier(n_neighbors=i)
    clf.fit(trainData, trainLabel)
    print("Test set accuracy with k = {:} : {:.2f}".format(i, clf.score(testData, testLabel)))

1      3
2      0
3      0
4      1
5      2
      ..
298    0
299    3
300    0
301    0
302    2
Name: ChestPain, Length: 297, dtype: int32
Test set accuracy with k = 1 : 0.67
Test set accuracy with k = 4 : 0.69
Test set accuracy with k = 7 : 0.80
Test set accuracy with k = 10 : 0.77
Test set accuracy with k = 13 : 0.79
Test set accuracy with k = 16 : 0.79
Test set accuracy with k = 19 : 0.77
Test set accuracy with k = 22 : 0.77
Test set accuracy with k = 25 : 0.76
Test set accuracy with k = 28 : 0.77

In [105]:
heart.iloc[:,0]

1      0.708333
2      0.791667
3      0.791667
4      0.166667
5      0.250000
         ...
298    0.583333
299    0.333333
300    0.812500
301    0.583333
302    0.583333
Name: Age, Length: 297, dtype: float64